[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "out"

# Next.js static export configuration
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/_next/image/*"
  to = "/_next/image/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Handle root path explicitly
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Handle all other paths with SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Ensure proper MIME types for static assets
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "*.json"
  [headers.values]
    Content-Type = "application/json"